/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApproverResponse,
} from '../models/index';
import {
    ApproverResponseFromJSON,
    ApproverResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class ApproverApi extends runtime.BaseAPI {

    /**
     */
    async apiApproverGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApproverResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Approver`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApproverResponseFromJSON));
    }

    /**
     */
    async apiApproverGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApproverResponse>> {
        const response = await this.apiApproverGetRaw(initOverrides);
        return await response.value();
    }

}
