/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CopropertyResponseListPagedResponse,
  ProblemDetails,
} from '../models/index';
import {
    CopropertyResponseListPagedResponseFromJSON,
    CopropertyResponseListPagedResponseToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface ApiCopropertyPlotRefGetRequest {
    plotRef: string;
    pageNumber?: number;
    pageSize?: number;
}

/**
 * 
 */
export class CopropertyApi extends runtime.BaseAPI {

    /**
     */
    async apiCopropertyPlotRefGetRaw(requestParameters: ApiCopropertyPlotRefGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CopropertyResponseListPagedResponse>> {
        if (requestParameters.plotRef === null || requestParameters.plotRef === undefined) {
            throw new runtime.RequiredError('plotRef','Required parameter requestParameters.plotRef was null or undefined when calling apiCopropertyPlotRefGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.pageNumber !== undefined) {
            queryParameters['PageNumber'] = requestParameters.pageNumber;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['PageSize'] = requestParameters.pageSize;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Coproperty/{plotRef}`.replace(`{${"plotRef"}}`, encodeURIComponent(String(requestParameters.plotRef))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CopropertyResponseListPagedResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCopropertyPlotRefGet(requestParameters: ApiCopropertyPlotRefGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CopropertyResponseListPagedResponse> {
        const response = await this.apiCopropertyPlotRefGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
