/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AffCalculation,
} from '../models/index';
import {
    AffCalculationFromJSON,
    AffCalculationToJSON,
} from '../models/index';

export interface ApiSummaryAffIdGetRequest {
    affId: number;
}

/**
 * 
 */
export class SummaryApi extends runtime.BaseAPI {

    /**
     */
    async apiSummaryAffIdGetRaw(requestParameters: ApiSummaryAffIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AffCalculation>> {
        if (requestParameters.affId === null || requestParameters.affId === undefined) {
            throw new runtime.RequiredError('affId','Required parameter requestParameters.affId was null or undefined when calling apiSummaryAffIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Summary/{affId}`.replace(`{${"affId"}}`, encodeURIComponent(String(requestParameters.affId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AffCalculationFromJSON(jsonValue));
    }

    /**
     */
    async apiSummaryAffIdGet(requestParameters: ApiSummaryAffIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AffCalculation> {
        const response = await this.apiSummaryAffIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiSummaryGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AffCalculation>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Summary`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AffCalculationFromJSON));
    }

    /**
     */
    async apiSummaryGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AffCalculation>> {
        const response = await this.apiSummaryGetRaw(initOverrides);
        return await response.value();
    }

}
