/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AffCalculationVersion } from './AffCalculationVersion';
import {
    AffCalculationVersionFromJSON,
    AffCalculationVersionFromJSONTyped,
    AffCalculationVersionToJSON,
} from './AffCalculationVersion';

/**
 * 
 * @export
 * @interface AffCalculation
 */
export interface AffCalculation {
    /**
     * 
     * @type {number}
     * @memberof AffCalculation
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof AffCalculation
     */
    affId?: number;
    /**
     * 
     * @type {number}
     * @memberof AffCalculation
     */
    gfa?: number;
    /**
     * 
     * @type {string}
     * @memberof AffCalculation
     */
    ref?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AffCalculation
     */
    displayName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AffCalculation
     */
    affCharges?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AffCalculation
     */
    afmCharges?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AffCalculation
     */
    percentageWeightedArea?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AffCalculation
     */
    percentageTantiemesAFMCharges?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AffCalculation
     */
    percentageTantiemesAFMVotes?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof AffCalculation
     */
    isActive?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof AffCalculation
     */
    weightedArea?: number;
    /**
     * 
     * @type {number}
     * @memberof AffCalculation
     */
    tantiemesAFMVotes?: number;
    /**
     * 
     * @type {number}
     * @memberof AffCalculation
     */
    tantiemesAFFVotes?: number;
    /**
     * 
     * @type {number}
     * @memberof AffCalculation
     */
    tantiemesAFFCharges?: number;
    /**
     * 
     * @type {number}
     * @memberof AffCalculation
     */
    tantiemesAFMCharges?: number;
    /**
     * 
     * @type {number}
     * @memberof AffCalculation
     */
    chargesAFM?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AffCalculation
     */
    chargesAff?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AffCalculation
     */
    affCalculationVersionId?: number;
    /**
     * 
     * @type {AffCalculationVersion}
     * @memberof AffCalculation
     */
    affCalculationVersion?: AffCalculationVersion;
    /**
     * 
     * @type {Date}
     * @memberof AffCalculation
     */
    createdAt?: Date | null;
}

/**
 * Check if a given object implements the AffCalculation interface.
 */
export function instanceOfAffCalculation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AffCalculationFromJSON(json: any): AffCalculation {
    return AffCalculationFromJSONTyped(json, false);
}

export function AffCalculationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AffCalculation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'affId': !exists(json, 'affId') ? undefined : json['affId'],
        'gfa': !exists(json, 'gfa') ? undefined : json['gfa'],
        'ref': !exists(json, 'ref') ? undefined : json['ref'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'affCharges': !exists(json, 'affCharges') ? undefined : json['affCharges'],
        'afmCharges': !exists(json, 'afmCharges') ? undefined : json['afmCharges'],
        'percentageWeightedArea': !exists(json, 'percentageWeightedArea') ? undefined : json['percentageWeightedArea'],
        'percentageTantiemesAFMCharges': !exists(json, 'percentageTantiemesAFMCharges') ? undefined : json['percentageTantiemesAFMCharges'],
        'percentageTantiemesAFMVotes': !exists(json, 'percentageTantiemesAFMVotes') ? undefined : json['percentageTantiemesAFMVotes'],
        'isActive': !exists(json, 'isActive') ? undefined : json['isActive'],
        'weightedArea': !exists(json, 'weightedArea') ? undefined : json['weightedArea'],
        'tantiemesAFMVotes': !exists(json, 'tantiemesAFMVotes') ? undefined : json['tantiemesAFMVotes'],
        'tantiemesAFFVotes': !exists(json, 'tantiemesAFFVotes') ? undefined : json['tantiemesAFFVotes'],
        'tantiemesAFFCharges': !exists(json, 'tantiemesAFFCharges') ? undefined : json['tantiemesAFFCharges'],
        'tantiemesAFMCharges': !exists(json, 'tantiemesAFMCharges') ? undefined : json['tantiemesAFMCharges'],
        'chargesAFM': !exists(json, 'chargesAFM') ? undefined : json['chargesAFM'],
        'chargesAff': !exists(json, 'chargesAff') ? undefined : json['chargesAff'],
        'affCalculationVersionId': !exists(json, 'affCalculationVersionId') ? undefined : json['affCalculationVersionId'],
        'affCalculationVersion': !exists(json, 'affCalculationVersion') ? undefined : AffCalculationVersionFromJSON(json['affCalculationVersion']),
        'createdAt': !exists(json, 'createdAt') ? undefined : (json['createdAt'] === null ? null : new Date(json['createdAt'])),
    };
}

export function AffCalculationToJSON(value?: AffCalculation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'affId': value.affId,
        'gfa': value.gfa,
        'ref': value.ref,
        'displayName': value.displayName,
        'affCharges': value.affCharges,
        'afmCharges': value.afmCharges,
        'percentageWeightedArea': value.percentageWeightedArea,
        'percentageTantiemesAFMCharges': value.percentageTantiemesAFMCharges,
        'percentageTantiemesAFMVotes': value.percentageTantiemesAFMVotes,
        'isActive': value.isActive,
        'weightedArea': value.weightedArea,
        'tantiemesAFMVotes': value.tantiemesAFMVotes,
        'tantiemesAFFVotes': value.tantiemesAFFVotes,
        'tantiemesAFFCharges': value.tantiemesAFFCharges,
        'tantiemesAFMCharges': value.tantiemesAFMCharges,
        'chargesAFM': value.chargesAFM,
        'chargesAff': value.chargesAff,
        'affCalculationVersionId': value.affCalculationVersionId,
        'affCalculationVersion': AffCalculationVersionToJSON(value.affCalculationVersion),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt === null ? null : value.createdAt.toISOString()),
    };
}

