/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Aff } from './Aff';
import {
    AffFromJSON,
    AffFromJSONTyped,
    AffToJSON,
} from './Aff';
import type { ModelConfiguration } from './ModelConfiguration';
import {
    ModelConfigurationFromJSON,
    ModelConfigurationFromJSONTyped,
    ModelConfigurationToJSON,
} from './ModelConfiguration';

/**
 * 
 * @export
 * @interface AffExpense
 */
export interface AffExpense {
    /**
     * 
     * @type {number}
     * @memberof AffExpense
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof AffExpense
     */
    totalCharge?: number;
    /**
     * 
     * @type {number}
     * @memberof AffExpense
     */
    affId?: number;
    /**
     * 
     * @type {Aff}
     * @memberof AffExpense
     */
    aff?: Aff;
    /**
     * 
     * @type {number}
     * @memberof AffExpense
     */
    configurationId?: number;
    /**
     * 
     * @type {ModelConfiguration}
     * @memberof AffExpense
     */
    _configuration?: ModelConfiguration;
    /**
     * 
     * @type {Date}
     * @memberof AffExpense
     */
    createdAt?: Date | null;
}

/**
 * Check if a given object implements the AffExpense interface.
 */
export function instanceOfAffExpense(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AffExpenseFromJSON(json: any): AffExpense {
    return AffExpenseFromJSONTyped(json, false);
}

export function AffExpenseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AffExpense {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'totalCharge': !exists(json, 'totalCharge') ? undefined : json['totalCharge'],
        'affId': !exists(json, 'affId') ? undefined : json['affId'],
        'aff': !exists(json, 'aff') ? undefined : AffFromJSON(json['aff']),
        'configurationId': !exists(json, 'configurationId') ? undefined : json['configurationId'],
        '_configuration': !exists(json, 'configuration') ? undefined : ModelConfigurationFromJSON(json['configuration']),
        'createdAt': !exists(json, 'createdAt') ? undefined : (json['createdAt'] === null ? null : new Date(json['createdAt'])),
    };
}

export function AffExpenseToJSON(value?: AffExpense | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'totalCharge': value.totalCharge,
        'affId': value.affId,
        'aff': AffToJSON(value.aff),
        'configurationId': value.configurationId,
        'configuration': ModelConfigurationToJSON(value._configuration),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt === null ? null : value.createdAt.toISOString()),
    };
}

