/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AfmCalculation } from './AfmCalculation';
import {
    AfmCalculationFromJSON,
    AfmCalculationFromJSONTyped,
    AfmCalculationToJSON,
} from './AfmCalculation';
import type { AfmExpense } from './AfmExpense';
import {
    AfmExpenseFromJSON,
    AfmExpenseFromJSONTyped,
    AfmExpenseToJSON,
} from './AfmExpense';
import type { AfmExpenseItem } from './AfmExpenseItem';
import {
    AfmExpenseItemFromJSON,
    AfmExpenseItemFromJSONTyped,
    AfmExpenseItemToJSON,
} from './AfmExpenseItem';
import type { CommonSpace } from './CommonSpace';
import {
    CommonSpaceFromJSON,
    CommonSpaceFromJSONTyped,
    CommonSpaceToJSON,
} from './CommonSpace';

/**
 * 
 * @export
 * @interface Afm
 */
export interface Afm {
    /**
     * 
     * @type {number}
     * @memberof Afm
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Afm
     */
    ref: string;
    /**
     * 
     * @type {string}
     * @memberof Afm
     */
    displayName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Afm
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Afm
     */
    totalGisArea?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Afm
     */
    totalRoadLength?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Afm
     */
    totalNoOfStreetLights?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Afm
     */
    totalAreaOfRoadSurface?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Afm
     */
    totalAreaOfGreenSpace?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof Afm
     */
    isActive?: boolean | null;
    /**
     * 
     * @type {Date}
     * @memberof Afm
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Array<CommonSpace>}
     * @memberof Afm
     */
    commonSpaces?: Array<CommonSpace> | null;
    /**
     * 
     * @type {Array<AfmCalculation>}
     * @memberof Afm
     */
    afmCalculations?: Array<AfmCalculation> | null;
    /**
     * 
     * @type {Array<AfmExpense>}
     * @memberof Afm
     */
    afmExpenses?: Array<AfmExpense> | null;
    /**
     * 
     * @type {Array<AfmExpenseItem>}
     * @memberof Afm
     */
    afmExpenseItems?: Array<AfmExpenseItem> | null;
}

/**
 * Check if a given object implements the Afm interface.
 */
export function instanceOfAfm(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "ref" in value;

    return isInstance;
}

export function AfmFromJSON(json: any): Afm {
    return AfmFromJSONTyped(json, false);
}

export function AfmFromJSONTyped(json: any, ignoreDiscriminator: boolean): Afm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ref': json['ref'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'totalGisArea': !exists(json, 'totalGisArea') ? undefined : json['totalGisArea'],
        'totalRoadLength': !exists(json, 'totalRoadLength') ? undefined : json['totalRoadLength'],
        'totalNoOfStreetLights': !exists(json, 'totalNoOfStreetLights') ? undefined : json['totalNoOfStreetLights'],
        'totalAreaOfRoadSurface': !exists(json, 'totalAreaOfRoadSurface') ? undefined : json['totalAreaOfRoadSurface'],
        'totalAreaOfGreenSpace': !exists(json, 'totalAreaOfGreenSpace') ? undefined : json['totalAreaOfGreenSpace'],
        'isActive': !exists(json, 'isActive') ? undefined : json['isActive'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (json['createdAt'] === null ? null : new Date(json['createdAt'])),
        'commonSpaces': !exists(json, 'commonSpaces') ? undefined : (json['commonSpaces'] === null ? null : (json['commonSpaces'] as Array<any>).map(CommonSpaceFromJSON)),
        'afmCalculations': !exists(json, 'afmCalculations') ? undefined : (json['afmCalculations'] === null ? null : (json['afmCalculations'] as Array<any>).map(AfmCalculationFromJSON)),
        'afmExpenses': !exists(json, 'afmExpenses') ? undefined : (json['afmExpenses'] === null ? null : (json['afmExpenses'] as Array<any>).map(AfmExpenseFromJSON)),
        'afmExpenseItems': !exists(json, 'afmExpenseItems') ? undefined : (json['afmExpenseItems'] === null ? null : (json['afmExpenseItems'] as Array<any>).map(AfmExpenseItemFromJSON)),
    };
}

export function AfmToJSON(value?: Afm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'ref': value.ref,
        'displayName': value.displayName,
        'description': value.description,
        'totalGisArea': value.totalGisArea,
        'totalRoadLength': value.totalRoadLength,
        'totalNoOfStreetLights': value.totalNoOfStreetLights,
        'totalAreaOfRoadSurface': value.totalAreaOfRoadSurface,
        'totalAreaOfGreenSpace': value.totalAreaOfGreenSpace,
        'isActive': value.isActive,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt === null ? null : value.createdAt.toISOString()),
        'commonSpaces': value.commonSpaces === undefined ? undefined : (value.commonSpaces === null ? null : (value.commonSpaces as Array<any>).map(CommonSpaceToJSON)),
        'afmCalculations': value.afmCalculations === undefined ? undefined : (value.afmCalculations === null ? null : (value.afmCalculations as Array<any>).map(AfmCalculationToJSON)),
        'afmExpenses': value.afmExpenses === undefined ? undefined : (value.afmExpenses === null ? null : (value.afmExpenses as Array<any>).map(AfmExpenseToJSON)),
        'afmExpenseItems': value.afmExpenseItems === undefined ? undefined : (value.afmExpenseItems === null ? null : (value.afmExpenseItems as Array<any>).map(AfmExpenseItemToJSON)),
    };
}

