/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Afm } from './Afm';
import {
    AfmFromJSON,
    AfmFromJSONTyped,
    AfmToJSON,
} from './Afm';
import type { AfmCalculationVersion } from './AfmCalculationVersion';
import {
    AfmCalculationVersionFromJSON,
    AfmCalculationVersionFromJSONTyped,
    AfmCalculationVersionToJSON,
} from './AfmCalculationVersion';

/**
 * 
 * @export
 * @interface AfmCalculation
 */
export interface AfmCalculation {
    /**
     * 
     * @type {number}
     * @memberof AfmCalculation
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof AfmCalculation
     */
    afmId?: number;
    /**
     * 
     * @type {Afm}
     * @memberof AfmCalculation
     */
    afm?: Afm;
    /**
     * 
     * @type {number}
     * @memberof AfmCalculation
     */
    gfa?: number;
    /**
     * 
     * @type {number}
     * @memberof AfmCalculation
     */
    weightedArea?: number;
    /**
     * 
     * @type {number}
     * @memberof AfmCalculation
     */
    tantiemesAFMVotes?: number;
    /**
     * 
     * @type {number}
     * @memberof AfmCalculation
     */
    tantiemesAFFVotes?: number;
    /**
     * 
     * @type {number}
     * @memberof AfmCalculation
     */
    tantiemesAFMCharges?: number;
    /**
     * 
     * @type {number}
     * @memberof AfmCalculation
     */
    tantiemesAFFCharges?: number;
    /**
     * 
     * @type {number}
     * @memberof AfmCalculation
     */
    chargesAFF?: number;
    /**
     * 
     * @type {number}
     * @memberof AfmCalculation
     */
    chargesAFM?: number;
    /**
     * 
     * @type {number}
     * @memberof AfmCalculation
     */
    afmCalculationVersionId?: number;
    /**
     * 
     * @type {AfmCalculationVersion}
     * @memberof AfmCalculation
     */
    afmCalculationVersion?: AfmCalculationVersion;
    /**
     * 
     * @type {Date}
     * @memberof AfmCalculation
     */
    createdAt?: Date | null;
}

/**
 * Check if a given object implements the AfmCalculation interface.
 */
export function instanceOfAfmCalculation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AfmCalculationFromJSON(json: any): AfmCalculation {
    return AfmCalculationFromJSONTyped(json, false);
}

export function AfmCalculationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AfmCalculation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'afmId': !exists(json, 'afmId') ? undefined : json['afmId'],
        'afm': !exists(json, 'afm') ? undefined : AfmFromJSON(json['afm']),
        'gfa': !exists(json, 'gfa') ? undefined : json['gfa'],
        'weightedArea': !exists(json, 'weightedArea') ? undefined : json['weightedArea'],
        'tantiemesAFMVotes': !exists(json, 'tantiemesAFMVotes') ? undefined : json['tantiemesAFMVotes'],
        'tantiemesAFFVotes': !exists(json, 'tantiemesAFFVotes') ? undefined : json['tantiemesAFFVotes'],
        'tantiemesAFMCharges': !exists(json, 'tantiemesAFMCharges') ? undefined : json['tantiemesAFMCharges'],
        'tantiemesAFFCharges': !exists(json, 'tantiemesAFFCharges') ? undefined : json['tantiemesAFFCharges'],
        'chargesAFF': !exists(json, 'chargesAFF') ? undefined : json['chargesAFF'],
        'chargesAFM': !exists(json, 'chargesAFM') ? undefined : json['chargesAFM'],
        'afmCalculationVersionId': !exists(json, 'afmCalculationVersionId') ? undefined : json['afmCalculationVersionId'],
        'afmCalculationVersion': !exists(json, 'afmCalculationVersion') ? undefined : AfmCalculationVersionFromJSON(json['afmCalculationVersion']),
        'createdAt': !exists(json, 'createdAt') ? undefined : (json['createdAt'] === null ? null : new Date(json['createdAt'])),
    };
}

export function AfmCalculationToJSON(value?: AfmCalculation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'afmId': value.afmId,
        'afm': AfmToJSON(value.afm),
        'gfa': value.gfa,
        'weightedArea': value.weightedArea,
        'tantiemesAFMVotes': value.tantiemesAFMVotes,
        'tantiemesAFFVotes': value.tantiemesAFFVotes,
        'tantiemesAFMCharges': value.tantiemesAFMCharges,
        'tantiemesAFFCharges': value.tantiemesAFFCharges,
        'chargesAFF': value.chargesAFF,
        'chargesAFM': value.chargesAFM,
        'afmCalculationVersionId': value.afmCalculationVersionId,
        'afmCalculationVersion': AfmCalculationVersionToJSON(value.afmCalculationVersion),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt === null ? null : value.createdAt.toISOString()),
    };
}

