/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AfmExpenseItemsVersion
 */
export interface AfmExpenseItemsVersion {
    /**
     * 
     * @type {number}
     * @memberof AfmExpenseItemsVersion
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AfmExpenseItemsVersion
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AfmExpenseItemsVersion
     */
    version?: number;
    /**
     * 
     * @type {Date}
     * @memberof AfmExpenseItemsVersion
     */
    yearStart?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof AfmExpenseItemsVersion
     */
    yearEnd?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof AfmExpenseItemsVersion
     */
    createdAt?: Date | null;
}

/**
 * Check if a given object implements the AfmExpenseItemsVersion interface.
 */
export function instanceOfAfmExpenseItemsVersion(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AfmExpenseItemsVersionFromJSON(json: any): AfmExpenseItemsVersion {
    return AfmExpenseItemsVersionFromJSONTyped(json, false);
}

export function AfmExpenseItemsVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AfmExpenseItemsVersion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'yearStart': !exists(json, 'yearStart') ? undefined : (json['yearStart'] === null ? null : new Date(json['yearStart'])),
        'yearEnd': !exists(json, 'yearEnd') ? undefined : (json['yearEnd'] === null ? null : new Date(json['yearEnd'])),
        'createdAt': !exists(json, 'createdAt') ? undefined : (json['createdAt'] === null ? null : new Date(json['createdAt'])),
    };
}

export function AfmExpenseItemsVersionToJSON(value?: AfmExpenseItemsVersion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'version': value.version,
        'yearStart': value.yearStart === undefined ? undefined : (value.yearStart === null ? null : value.yearStart.toISOString()),
        'yearEnd': value.yearEnd === undefined ? undefined : (value.yearEnd === null ? null : value.yearEnd.toISOString()),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt === null ? null : value.createdAt.toISOString()),
    };
}

