/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Afm } from './Afm';
import {
    AfmFromJSON,
    AfmFromJSONTyped,
    AfmToJSON,
} from './Afm';

/**
 * 
 * @export
 * @interface AfmExpense
 */
export interface AfmExpense {
    /**
     * 
     * @type {number}
     * @memberof AfmExpense
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AfmExpense
     */
    ref?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AfmExpense
     */
    displayName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AfmExpense
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AfmExpense
     */
    afmId?: number;
    /**
     * 
     * @type {Afm}
     * @memberof AfmExpense
     */
    afm?: Afm;
    /**
     * 
     * @type {number}
     * @memberof AfmExpense
     */
    totalCharge?: number;
    /**
     * 
     * @type {Date}
     * @memberof AfmExpense
     */
    createdAt?: Date | null;
}

/**
 * Check if a given object implements the AfmExpense interface.
 */
export function instanceOfAfmExpense(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AfmExpenseFromJSON(json: any): AfmExpense {
    return AfmExpenseFromJSONTyped(json, false);
}

export function AfmExpenseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AfmExpense {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ref': !exists(json, 'ref') ? undefined : json['ref'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'afmId': !exists(json, 'afmId') ? undefined : json['afmId'],
        'afm': !exists(json, 'afm') ? undefined : AfmFromJSON(json['afm']),
        'totalCharge': !exists(json, 'totalCharge') ? undefined : json['totalCharge'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (json['createdAt'] === null ? null : new Date(json['createdAt'])),
    };
}

export function AfmExpenseToJSON(value?: AfmExpense | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'ref': value.ref,
        'displayName': value.displayName,
        'description': value.description,
        'afmId': value.afmId,
        'afm': AfmToJSON(value.afm),
        'totalCharge': value.totalCharge,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt === null ? null : value.createdAt.toISOString()),
    };
}

