/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApproverResponse
 */
export interface ApproverResponse {
    /**
     * 
     * @type {number}
     * @memberof ApproverResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ApproverResponse
     */
    userId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApproverResponse
     */
    name?: string | null;
}

/**
 * Check if a given object implements the ApproverResponse interface.
 */
export function instanceOfApproverResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApproverResponseFromJSON(json: any): ApproverResponse {
    return ApproverResponseFromJSONTyped(json, false);
}

export function ApproverResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApproverResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function ApproverResponseToJSON(value?: ApproverResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userId': value.userId,
        'name': value.name,
    };
}

