/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangeRequestBody
 */
export interface ChangeRequestBody {
    /**
     * 
     * @type {number}
     * @memberof ChangeRequestBody
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ChangeRequestBody
     */
    statusId?: number;
}

/**
 * Check if a given object implements the ChangeRequestBody interface.
 */
export function instanceOfChangeRequestBody(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChangeRequestBodyFromJSON(json: any): ChangeRequestBody {
    return ChangeRequestBodyFromJSONTyped(json, false);
}

export function ChangeRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'statusId': !exists(json, 'statusId') ? undefined : json['statusId'],
    };
}

export function ChangeRequestBodyToJSON(value?: ChangeRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'statusId': value.statusId,
    };
}

