/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CommonSpaceResponse } from './CommonSpaceResponse';
import {
    CommonSpaceResponseFromJSON,
    CommonSpaceResponseFromJSONTyped,
    CommonSpaceResponseToJSON,
} from './CommonSpaceResponse';

/**
 * 
 * @export
 * @interface CommonSpaceResponseListPagedResponse
 */
export interface CommonSpaceResponseListPagedResponse {
    /**
     * 
     * @type {Array<CommonSpaceResponse>}
     * @memberof CommonSpaceResponseListPagedResponse
     */
    data?: Array<CommonSpaceResponse> | null;
    /**
     * 
     * @type {boolean}
     * @memberof CommonSpaceResponseListPagedResponse
     */
    succeeded?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof CommonSpaceResponseListPagedResponse
     */
    errors?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof CommonSpaceResponseListPagedResponse
     */
    message?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CommonSpaceResponseListPagedResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof CommonSpaceResponseListPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {string}
     * @memberof CommonSpaceResponseListPagedResponse
     */
    firstPage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CommonSpaceResponseListPagedResponse
     */
    lastPage?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CommonSpaceResponseListPagedResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof CommonSpaceResponseListPagedResponse
     */
    totalRecords?: number;
    /**
     * 
     * @type {string}
     * @memberof CommonSpaceResponseListPagedResponse
     */
    nextPage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CommonSpaceResponseListPagedResponse
     */
    previousPage?: string | null;
}

/**
 * Check if a given object implements the CommonSpaceResponseListPagedResponse interface.
 */
export function instanceOfCommonSpaceResponseListPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CommonSpaceResponseListPagedResponseFromJSON(json: any): CommonSpaceResponseListPagedResponse {
    return CommonSpaceResponseListPagedResponseFromJSONTyped(json, false);
}

export function CommonSpaceResponseListPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonSpaceResponseListPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(CommonSpaceResponseFromJSON)),
        'succeeded': !exists(json, 'succeeded') ? undefined : json['succeeded'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'pageNumber': !exists(json, 'pageNumber') ? undefined : json['pageNumber'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'firstPage': !exists(json, 'firstPage') ? undefined : json['firstPage'],
        'lastPage': !exists(json, 'lastPage') ? undefined : json['lastPage'],
        'totalPages': !exists(json, 'totalPages') ? undefined : json['totalPages'],
        'totalRecords': !exists(json, 'totalRecords') ? undefined : json['totalRecords'],
        'nextPage': !exists(json, 'nextPage') ? undefined : json['nextPage'],
        'previousPage': !exists(json, 'previousPage') ? undefined : json['previousPage'],
    };
}

export function CommonSpaceResponseListPagedResponseToJSON(value?: CommonSpaceResponseListPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(CommonSpaceResponseToJSON)),
        'succeeded': value.succeeded,
        'errors': value.errors,
        'message': value.message,
        'pageNumber': value.pageNumber,
        'pageSize': value.pageSize,
        'firstPage': value.firstPage,
        'lastPage': value.lastPage,
        'totalPages': value.totalPages,
        'totalRecords': value.totalRecords,
        'nextPage': value.nextPage,
        'previousPage': value.previousPage,
    };
}

