/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CopropertyResponse
 */
export interface CopropertyResponse {
    /**
     * 
     * @type {number}
     * @memberof CopropertyResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CopropertyResponse
     */
    ref?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CopropertyResponse
     */
    displayName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CopropertyResponse
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CopropertyResponse
     */
    gisArea?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CopropertyResponse
     */
    chargesAFF?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CopropertyResponse
     */
    chargesAFM?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CopropertyResponse
     */
    levy?: number | null;
}

/**
 * Check if a given object implements the CopropertyResponse interface.
 */
export function instanceOfCopropertyResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CopropertyResponseFromJSON(json: any): CopropertyResponse {
    return CopropertyResponseFromJSONTyped(json, false);
}

export function CopropertyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CopropertyResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ref': !exists(json, 'ref') ? undefined : json['ref'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'gisArea': !exists(json, 'gisArea') ? undefined : json['gisArea'],
        'chargesAFF': !exists(json, 'chargesAFF') ? undefined : json['chargesAFF'],
        'chargesAFM': !exists(json, 'chargesAFM') ? undefined : json['chargesAFM'],
        'levy': !exists(json, 'levy') ? undefined : json['levy'],
    };
}

export function CopropertyResponseToJSON(value?: CopropertyResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'ref': value.ref,
        'displayName': value.displayName,
        'description': value.description,
        'gisArea': value.gisArea,
        'chargesAFF': value.chargesAFF,
        'chargesAFM': value.chargesAFM,
        'levy': value.levy,
    };
}

