/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CopropertyResponse } from './CopropertyResponse';
import {
    CopropertyResponseFromJSON,
    CopropertyResponseFromJSONTyped,
    CopropertyResponseToJSON,
} from './CopropertyResponse';

/**
 * 
 * @export
 * @interface CopropertyResponseListPagedResponse
 */
export interface CopropertyResponseListPagedResponse {
    /**
     * 
     * @type {Array<CopropertyResponse>}
     * @memberof CopropertyResponseListPagedResponse
     */
    data?: Array<CopropertyResponse> | null;
    /**
     * 
     * @type {boolean}
     * @memberof CopropertyResponseListPagedResponse
     */
    succeeded?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof CopropertyResponseListPagedResponse
     */
    errors?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof CopropertyResponseListPagedResponse
     */
    message?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CopropertyResponseListPagedResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof CopropertyResponseListPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {string}
     * @memberof CopropertyResponseListPagedResponse
     */
    firstPage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CopropertyResponseListPagedResponse
     */
    lastPage?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CopropertyResponseListPagedResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof CopropertyResponseListPagedResponse
     */
    totalRecords?: number;
    /**
     * 
     * @type {string}
     * @memberof CopropertyResponseListPagedResponse
     */
    nextPage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CopropertyResponseListPagedResponse
     */
    previousPage?: string | null;
}

/**
 * Check if a given object implements the CopropertyResponseListPagedResponse interface.
 */
export function instanceOfCopropertyResponseListPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CopropertyResponseListPagedResponseFromJSON(json: any): CopropertyResponseListPagedResponse {
    return CopropertyResponseListPagedResponseFromJSONTyped(json, false);
}

export function CopropertyResponseListPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CopropertyResponseListPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(CopropertyResponseFromJSON)),
        'succeeded': !exists(json, 'succeeded') ? undefined : json['succeeded'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'pageNumber': !exists(json, 'pageNumber') ? undefined : json['pageNumber'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'firstPage': !exists(json, 'firstPage') ? undefined : json['firstPage'],
        'lastPage': !exists(json, 'lastPage') ? undefined : json['lastPage'],
        'totalPages': !exists(json, 'totalPages') ? undefined : json['totalPages'],
        'totalRecords': !exists(json, 'totalRecords') ? undefined : json['totalRecords'],
        'nextPage': !exists(json, 'nextPage') ? undefined : json['nextPage'],
        'previousPage': !exists(json, 'previousPage') ? undefined : json['previousPage'],
    };
}

export function CopropertyResponseListPagedResponseToJSON(value?: CopropertyResponseListPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(CopropertyResponseToJSON)),
        'succeeded': value.succeeded,
        'errors': value.errors,
        'message': value.message,
        'pageNumber': value.pageNumber,
        'pageSize': value.pageSize,
        'firstPage': value.firstPage,
        'lastPage': value.lastPage,
        'totalPages': value.totalPages,
        'totalRecords': value.totalRecords,
        'nextPage': value.nextPage,
        'previousPage': value.previousPage,
    };
}

