/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateResponse
 */
export interface CreateResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateResponse
     */
    message?: string | null;
}

/**
 * Check if a given object implements the CreateResponse interface.
 */
export function instanceOfCreateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateResponseFromJSON(json: any): CreateResponse {
    return CreateResponseFromJSONTyped(json, false);
}

export function CreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function CreateResponseToJSON(value?: CreateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

