/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExpenseItemResponse
 */
export interface ExpenseItemResponse {
    /**
     * 
     * @type {number}
     * @memberof ExpenseItemResponse
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseItemResponse
     */
    expenseId?: number;
    /**
     * 
     * @type {string}
     * @memberof ExpenseItemResponse
     */
    expenseDisplayName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExpenseItemResponse
     */
    expenseUnitDisplayName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExpenseItemResponse
     */
    expenseUnitRef?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ExpenseItemResponse
     */
    rate?: number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseItemResponse
     */
    derivedMultiplier?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ExpenseItemResponse
     */
    derivedValue?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ExpenseItemResponse
     */
    expenseRef?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExpenseItemResponse
     */
    expenseCategoryRef?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExpenseItemResponse
     */
    multiplierRef?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExpenseItemResponse
     */
    multiplierName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ExpenseItemResponse
     */
    afmId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ExpenseItemResponse
     */
    affId?: number | null;
}

/**
 * Check if a given object implements the ExpenseItemResponse interface.
 */
export function instanceOfExpenseItemResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ExpenseItemResponseFromJSON(json: any): ExpenseItemResponse {
    return ExpenseItemResponseFromJSONTyped(json, false);
}

export function ExpenseItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpenseItemResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'expenseId': !exists(json, 'expenseId') ? undefined : json['expenseId'],
        'expenseDisplayName': !exists(json, 'expenseDisplayName') ? undefined : json['expenseDisplayName'],
        'expenseUnitDisplayName': !exists(json, 'expenseUnitDisplayName') ? undefined : json['expenseUnitDisplayName'],
        'expenseUnitRef': !exists(json, 'expenseUnitRef') ? undefined : json['expenseUnitRef'],
        'rate': !exists(json, 'rate') ? undefined : json['rate'],
        'derivedMultiplier': !exists(json, 'derivedMultiplier') ? undefined : json['derivedMultiplier'],
        'derivedValue': !exists(json, 'derivedValue') ? undefined : json['derivedValue'],
        'expenseRef': !exists(json, 'expenseRef') ? undefined : json['expenseRef'],
        'expenseCategoryRef': !exists(json, 'expenseCategoryRef') ? undefined : json['expenseCategoryRef'],
        'multiplierRef': !exists(json, 'multiplierRef') ? undefined : json['multiplierRef'],
        'multiplierName': !exists(json, 'multiplierName') ? undefined : json['multiplierName'],
        'afmId': !exists(json, 'afmId') ? undefined : json['afmId'],
        'affId': !exists(json, 'affId') ? undefined : json['affId'],
    };
}

export function ExpenseItemResponseToJSON(value?: ExpenseItemResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'expenseId': value.expenseId,
        'expenseDisplayName': value.expenseDisplayName,
        'expenseUnitDisplayName': value.expenseUnitDisplayName,
        'expenseUnitRef': value.expenseUnitRef,
        'rate': value.rate,
        'derivedMultiplier': value.derivedMultiplier,
        'derivedValue': value.derivedValue,
        'expenseRef': value.expenseRef,
        'expenseCategoryRef': value.expenseCategoryRef,
        'multiplierRef': value.multiplierRef,
        'multiplierName': value.multiplierName,
        'afmId': value.afmId,
        'affId': value.affId,
    };
}

