/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ExpenseMultiplierValueTypes = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type ExpenseMultiplierValueTypes = typeof ExpenseMultiplierValueTypes[keyof typeof ExpenseMultiplierValueTypes];


export function ExpenseMultiplierValueTypesFromJSON(json: any): ExpenseMultiplierValueTypes {
    return ExpenseMultiplierValueTypesFromJSONTyped(json, false);
}

export function ExpenseMultiplierValueTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpenseMultiplierValueTypes {
    return json as ExpenseMultiplierValueTypes;
}

export function ExpenseMultiplierValueTypesToJSON(value?: ExpenseMultiplierValueTypes | null): any {
    return value as any;
}

