/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExpenseItem
 */
export interface ExpenseItem {
    /**
     * 
     * @type {number}
     * @memberof ExpenseItem
     */
    rate?: number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseItem
     */
    expenseId?: number;
}

/**
 * Check if a given object implements the ExpenseItem interface.
 */
export function instanceOfExpenseItem(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ExpenseItemFromJSON(json: any): ExpenseItem {
    return ExpenseItemFromJSONTyped(json, false);
}

export function ExpenseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpenseItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rate': !exists(json, 'rate') ? undefined : json['rate'],
        'expenseId': !exists(json, 'expenseId') ? undefined : json['expenseId'],
    };
}

export function ExpenseItemToJSON(value?: ExpenseItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rate': value.rate,
        'expenseId': value.expenseId,
    };
}

