/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExpenseMultiplierValueTypes } from './ExpenseMultiplierValueTypes';
import {
    ExpenseMultiplierValueTypesFromJSON,
    ExpenseMultiplierValueTypesFromJSONTyped,
    ExpenseMultiplierValueTypesToJSON,
} from './ExpenseMultiplierValueTypes';

/**
 * 
 * @export
 * @interface ExpenseMultiplier
 */
export interface ExpenseMultiplier {
    /**
     * 
     * @type {number}
     * @memberof ExpenseMultiplier
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ExpenseMultiplier
     */
    ref: string;
    /**
     * 
     * @type {string}
     * @memberof ExpenseMultiplier
     */
    displayName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExpenseMultiplier
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ExpenseMultiplier
     */
    value?: number | null;
    /**
     * 
     * @type {ExpenseMultiplierValueTypes}
     * @memberof ExpenseMultiplier
     */
    valueType?: ExpenseMultiplierValueTypes;
    /**
     * 
     * @type {Date}
     * @memberof ExpenseMultiplier
     */
    createdAt?: Date | null;
}

/**
 * Check if a given object implements the ExpenseMultiplier interface.
 */
export function instanceOfExpenseMultiplier(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "ref" in value;

    return isInstance;
}

export function ExpenseMultiplierFromJSON(json: any): ExpenseMultiplier {
    return ExpenseMultiplierFromJSONTyped(json, false);
}

export function ExpenseMultiplierFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpenseMultiplier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ref': json['ref'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'valueType': !exists(json, 'valueType') ? undefined : ExpenseMultiplierValueTypesFromJSON(json['valueType']),
        'createdAt': !exists(json, 'createdAt') ? undefined : (json['createdAt'] === null ? null : new Date(json['createdAt'])),
    };
}

export function ExpenseMultiplierToJSON(value?: ExpenseMultiplier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'ref': value.ref,
        'displayName': value.displayName,
        'description': value.description,
        'value': value.value,
        'valueType': ExpenseMultiplierValueTypesToJSON(value.valueType),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt === null ? null : value.createdAt.toISOString()),
    };
}

