/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlotChange
 */
export interface PlotChange {
    /**
     * 
     * @type {number}
     * @memberof PlotChange
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof PlotChange
     */
    plotStatusId?: number;
}

/**
 * Check if a given object implements the PlotChange interface.
 */
export function instanceOfPlotChange(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PlotChangeFromJSON(json: any): PlotChange {
    return PlotChangeFromJSONTyped(json, false);
}

export function PlotChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlotChange {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'plotStatusId': !exists(json, 'plotStatusId') ? undefined : json['plotStatusId'],
    };
}

export function PlotChangeToJSON(value?: PlotChange | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'plotStatusId': value.plotStatusId,
    };
}

