/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlotVersion
 */
export interface PlotVersion {
    /**
     * 
     * @type {number}
     * @memberof PlotVersion
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PlotVersion
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PlotVersion
     */
    version?: number;
    /**
     * 
     * @type {Date}
     * @memberof PlotVersion
     */
    createdAt?: Date | null;
}

/**
 * Check if a given object implements the PlotVersion interface.
 */
export function instanceOfPlotVersion(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PlotVersionFromJSON(json: any): PlotVersion {
    return PlotVersionFromJSONTyped(json, false);
}

export function PlotVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlotVersion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (json['createdAt'] === null ? null : new Date(json['createdAt'])),
    };
}

export function PlotVersionToJSON(value?: PlotVersion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'version': value.version,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt === null ? null : value.createdAt.toISOString()),
    };
}

