/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Plot } from './Plot';
import {
    PlotFromJSON,
    PlotFromJSONTyped,
    PlotToJSON,
} from './Plot';
import type { PlotCalculationVersion } from './PlotCalculationVersion';
import {
    PlotCalculationVersionFromJSON,
    PlotCalculationVersionFromJSONTyped,
    PlotCalculationVersionToJSON,
} from './PlotCalculationVersion';

/**
 * 
 * @export
 * @interface PlotCalculation
 */
export interface PlotCalculation {
    /**
     * 
     * @type {number}
     * @memberof PlotCalculation
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof PlotCalculation
     */
    plotId?: number;
    /**
     * 
     * @type {Plot}
     * @memberof PlotCalculation
     */
    plot?: Plot;
    /**
     * 
     * @type {number}
     * @memberof PlotCalculation
     */
    gfa?: number;
    /**
     * 
     * @type {number}
     * @memberof PlotCalculation
     */
    weightedArea?: number;
    /**
     * 
     * @type {number}
     * @memberof PlotCalculation
     */
    weightedAreaG?: number;
    /**
     * 
     * @type {number}
     * @memberof PlotCalculation
     */
    weightedAreaS?: number;
    /**
     * 
     * @type {number}
     * @memberof PlotCalculation
     */
    tantiemesAFMVotes?: number;
    /**
     * 
     * @type {number}
     * @memberof PlotCalculation
     */
    tantiemesAFFVotes?: number;
    /**
     * 
     * @type {number}
     * @memberof PlotCalculation
     */
    tantiemesAFMCharges?: number;
    /**
     * 
     * @type {number}
     * @memberof PlotCalculation
     */
    tantiemesAFFCharges?: number;
    /**
     * 
     * @type {number}
     * @memberof PlotCalculation
     */
    chargesAFF?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PlotCalculation
     */
    chargesAFM?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PlotCalculation
     */
    affId?: number;
    /**
     * 
     * @type {number}
     * @memberof PlotCalculation
     */
    plotCalculationVersionId?: number;
    /**
     * 
     * @type {PlotCalculationVersion}
     * @memberof PlotCalculation
     */
    plotCalculationVersion?: PlotCalculationVersion;
    /**
     * 
     * @type {Date}
     * @memberof PlotCalculation
     */
    createdAt?: Date | null;
}

/**
 * Check if a given object implements the PlotCalculation interface.
 */
export function instanceOfPlotCalculation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PlotCalculationFromJSON(json: any): PlotCalculation {
    return PlotCalculationFromJSONTyped(json, false);
}

export function PlotCalculationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlotCalculation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'plotId': !exists(json, 'plotId') ? undefined : json['plotId'],
        'plot': !exists(json, 'plot') ? undefined : PlotFromJSON(json['plot']),
        'gfa': !exists(json, 'gfa') ? undefined : json['gfa'],
        'weightedArea': !exists(json, 'weightedArea') ? undefined : json['weightedArea'],
        'weightedAreaG': !exists(json, 'weightedAreaG') ? undefined : json['weightedAreaG'],
        'weightedAreaS': !exists(json, 'weightedAreaS') ? undefined : json['weightedAreaS'],
        'tantiemesAFMVotes': !exists(json, 'tantiemesAFMVotes') ? undefined : json['tantiemesAFMVotes'],
        'tantiemesAFFVotes': !exists(json, 'tantiemesAFFVotes') ? undefined : json['tantiemesAFFVotes'],
        'tantiemesAFMCharges': !exists(json, 'tantiemesAFMCharges') ? undefined : json['tantiemesAFMCharges'],
        'tantiemesAFFCharges': !exists(json, 'tantiemesAFFCharges') ? undefined : json['tantiemesAFFCharges'],
        'chargesAFF': !exists(json, 'chargesAFF') ? undefined : json['chargesAFF'],
        'chargesAFM': !exists(json, 'chargesAFM') ? undefined : json['chargesAFM'],
        'affId': !exists(json, 'affId') ? undefined : json['affId'],
        'plotCalculationVersionId': !exists(json, 'plotCalculationVersionId') ? undefined : json['plotCalculationVersionId'],
        'plotCalculationVersion': !exists(json, 'plotCalculationVersion') ? undefined : PlotCalculationVersionFromJSON(json['plotCalculationVersion']),
        'createdAt': !exists(json, 'createdAt') ? undefined : (json['createdAt'] === null ? null : new Date(json['createdAt'])),
    };
}

export function PlotCalculationToJSON(value?: PlotCalculation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'plotId': value.plotId,
        'plot': PlotToJSON(value.plot),
        'gfa': value.gfa,
        'weightedArea': value.weightedArea,
        'weightedAreaG': value.weightedAreaG,
        'weightedAreaS': value.weightedAreaS,
        'tantiemesAFMVotes': value.tantiemesAFMVotes,
        'tantiemesAFFVotes': value.tantiemesAFFVotes,
        'tantiemesAFMCharges': value.tantiemesAFMCharges,
        'tantiemesAFFCharges': value.tantiemesAFFCharges,
        'chargesAFF': value.chargesAFF,
        'chargesAFM': value.chargesAFM,
        'affId': value.affId,
        'plotCalculationVersionId': value.plotCalculationVersionId,
        'plotCalculationVersion': PlotCalculationVersionToJSON(value.plotCalculationVersion),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt === null ? null : value.createdAt.toISOString()),
    };
}

