/* tslint:disable */
/* eslint-disable */
/**
 * Beau Plan Administrator\'s API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserBody
 */
export interface UserBody {
    /**
     * 
     * @type {string}
     * @memberof UserBody
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserBody
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserBody
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserBody
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserBody
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserBody
     */
    roleId?: string | null;
}

/**
 * Check if a given object implements the UserBody interface.
 */
export function instanceOfUserBody(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserBodyFromJSON(json: any): UserBody {
    return UserBodyFromJSONTyped(json, false);
}

export function UserBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'userName': !exists(json, 'userName') ? undefined : json['userName'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'roleId': !exists(json, 'roleId') ? undefined : json['roleId'],
    };
}

export function UserBodyToJSON(value?: UserBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firstName': value.firstName,
        'lastName': value.lastName,
        'email': value.email,
        'userName': value.userName,
        'password': value.password,
        'roleId': value.roleId,
    };
}

